# Generated by Django 2.0.5 on 2018-06-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180622_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
