# Generated by Django 2.0.5 on 2018-06-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180621_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Semester',
            field=models.IntegerField(default=2),
        ),
    ]
