# Generated by Django 2.0.5 on 2018-06-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180621_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Semester',
            field=models.CharField(max_length=5),
        ),
    ]
