# Generated by Django 2.0.5 on 2018-06-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20180621_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Semester',
            field=models.CharField(blank=True, default='2', max_length=5),
        ),
    ]
