# Generated by Django 2.0.5 on 2018-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20180621_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
