# Generated by Django 2.0.5 on 2018-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20180621_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Semester',
            field=models.CharField(default='2', max_length=5, null=True),
        ),
    ]
